### ISSUE TITLE
[Feature Request] as follow

### ISSUE THREAD

**Issue by nick-cjyx9** [WenqiOfficial/StudyWithMiku#13]
1. 导入歌单
2. 在线人数（后续还可以对接一个叫做”休息室“的 online chat room🤣）
（可以使用 umami 之类的统计代替不蒜子 vercel + supabase 成本为 0，也可以显示在线人数）
3. 关于排行榜：我的建议是没必要，但可以显示时长最久和总使用时长。

**Comment by WenqiOfficial** [comment]
感谢Issues！

回复：

1.**导入歌单**功能会加入，支持网易云、QQ、酷我等平台（啊经典metingjs）

2.umami统计的方法会去研究一下的！

3.排行榜这类的想作为~闲的不行再去做的功能~，做出时长最久和总使用时长后排行榜也可顺势加入这样

( •̀ ω •́ )✧

**Comment by nick-cjyx9** [comment]
好！如果用umami的话可以参考[我的博客](https://github.com/nick-cjyx9/ilesBlog/blob/main/src/composables/useUmami.ts)

**Comment by WenqiOfficial** [comment]
好！(｀・ω・´)
