### ISSUE TITLE
点击Study按钮没有反应

### ISSUE THREAD

**Issue by OldenAmber** [WenqiOfficial/StudyWithMiku#20]
只有Study按钮怎么按都没有反应，但是设置和关于是可以正常启动的

**Comment by OldenAmber** [comment]
好吧，我连了个魔法就能正常使用了。明明之前是可以直连的😂

**Comment by WenqiOfficial** [comment]
正常情况下是不需要魔法的•᷄ࡇ•᷅
如果可以的话能打开控制台将`Error`日志复制或者截图发送吗_(:зゝ∠)_

**Comment by OldenAmber** [comment]
![Screenshot 2023-08-14 105437](https://github.com/WenqiOfficial/StudyWithMiku/assets/124518888/80917a62-3757-4ed6-bd8c-27f53de6e140)
请问需要的是这个吗

**Comment by OldenAmber** [comment]
之前的情况是需要刷新多次才可以加载出主界面，但study仍是可以正常使用的。
连了clash之后可以秒连网站并且顺利打开study

**Comment by WenqiOfficial** [comment]
ヾ(≧∇≦感谢≧∇≦)ノ
umami未能加载完成导致的问题，下个版本会修复好的(･ω･)
