### ISSUE TITLE
[Feature] VIP歌曲屏蔽

### ISSUE THREAD

**Issue by dobblegg** [WenqiOfficial/StudyWithMiku#34]
### 简述

屏蔽VIP歌曲/链接账号

### 细节

您好！在使用该项目中出现了自定义歌单但是无法播放VIP歌曲的问题，请问能否加入直接筛选掉VIP歌曲的功能或选择将VIP歌曲？

**Comment by WenqiOfficial** [comment]
感谢反馈！

抱歉由于目前音乐播放使用的为 **APlayer+MetingJS** 的组合，API获取的为**整个歌单**的数据，所以目前还是无法做到VIP歌曲播放或屏蔽

如果有好的API可以解析VIP歌曲也欢迎提供( •̀ ω •́ )y
