### ISSUE TITLE
新增（可自选的）计时逻辑

### ISSUE THREAD

**Issue by YaoSiQian** [WenqiOfficial/StudyWithMiku#4]
言简意赅，就是在检测到**鼠标移动**或**键盘输入**的时候就暂停计时
不过建议可以在设置界面手动开启

~残忍又不失刻苦~

**Comment by WenqiOfficial** [comment]
加TODO了

~虽然还是要靠自觉力啦www（~

**Comment by KinseyD** [comment]
会不会是方向错了，如果碰电脑就暂停计时说明电脑不用于学习，甚至不应该打开；而用这个网站的朋友基本上都是需要电脑辅助学习，那这个功能就意义不大了，其他todo可能比这好些

**Comment by WenqiOfficial** [comment]
> 会不会是方向错了，如果碰电脑就暂停计时说明电脑不用于学习，甚至不应该打开；而用这个网站的朋友基本上都是需要电脑辅助学习，那这个功能就意义不大了，其他todo可能比这好些

确实大家基本上是用来辅助学习

不过也不会说只添加仅加入 检测键鼠输入后暂停，失去焦点后暂停 等等也会加入

下足决心了但是中途却想摸鱼的情况也是有的啦，所以我认为是可以加入TODO的，作为额外功能存在也挺好的嘛(｀・ω・´)

TODO还是会按照先提的功能顺序去做的(｀・ω・´)

**Comment by WenqiOfficial** [comment]
Merged.

( •̀ ω •́ )✧
