### ISSUE TITLE
part3的专辑发布了[Feature] 

### ISSUE THREAD

**Issue by LeukoFan** [WenqiOfficial/StudyWithMiku#47]
### 简述

大佬更新一下Study With Miku网页的歌单吧~

### 细节

part3_(≧∇≦」∠)_

**Comment by COSA-Project** [comment]
WenqiOfficial 已添加Part3歌曲

**Comment by WenqiOfficial** [comment]
Part3已经更新了，最近由于学业原因回复不是很及时，抱歉抱歉qwq
