### ISSUE TITLE
PART3出辣[Feature] 

### ISSUE THREAD

**Issue by SkyFa11er** [WenqiOfficial/StudyWithMiku#48]
### 简述

UPUP該加新歌了 >~</

### 细节

https://www.bilibili.com/video/BV1jw411n7BZ/?spm_id_from=333.788&vd_source=2cab20bd87847ad8c300a7652b13995e

**Comment by COSA-Project** [comment]
@WenqiOfficial 已添加Part3歌曲

**Comment by WenqiOfficial** [comment]
Part3已经更新了，最近由于学业原因回复不是很及时，抱歉抱歉qwq

**Comment by SkyFa11er** [comment]
> Part3已经更新了，最近由于学业原因回复不是很及时，抱歉抱歉qwq

沒事沒事，謝謝你制作了這個網址，期末月一直在用(･ω･)ﾉ
