### ISSUE TITLE
[Feature] 请添加Part3！

### ISSUE THREAD

**Issue by AsciiP** [WenqiOfficial/StudyWithMiku#51]
### 简述

STUDY WITH MIKU Part3更新了，作者大大能不能加一下;w;

### 细节

https://www.bilibili.com/video/BV1jw411n7BZ

**Comment by WenqiOfficial** [comment]
已经更新“关于”中的内容啦！

**Comment by WenqiOfficial** [comment]
前段时间只能更新到歌单，未能及时响应qwq
