### ISSUE TITLE
[Feature] 歌单列表操作优化

### ISSUE THREAD

**Issue by gkgkhssy** [WenqiOfficial/StudyWithMiku#55]
### 简述

点击别的地方能够关闭列表，下面是我简单的实现方法

### 细节

<script>
    $(() => {
      $("body").click((event) => {
        // 如果点击的是播放器、图标，或者播放器未展开，则直接返回
        if ($(event.target).closest(".aplayer").length) return;
        if ($(event.target)[0].nodeName == "svg" || $(event.target)[0].nodeName == "path") return;
        if ($(".aplayer-narrow").length) return;

        // 如果播放列表已展开，则收起列表，否则收起播放器
        if (!$(".aplayer-list-hide").length) { $(".aplayer-icon-menu").click(); }
        else {
          // 如果是移动端则不收起播放器
          if (/(iPhone|iPad|iPod|Android|webOS|BlackBerry|Opera Mini|IEMobile)/i.test(navigator.userAgent)) return;

          $(".aplayer-miniswitcher").click();
        }
      });
    })
  </script>

**Comment by WenqiOfficial** [comment]
是个不错的功能建议！
