### ISSUE TITLE
可以试试Cloudflare Pages

### ISSUE THREAD

**Issue by MHYCWasTaken** [WenqiOfficial/StudyWithMiku#6]
Cloudflare比Github快些, 而且部署也快  
好像有国内连不上github.io的

**Comment by WenqiOfficial** [comment]
## 蟹蟹你的建议！(｀・ω・´)

目前是使用Vercel来托管的，而Cloudflare网络其实在国内也**不是都能连上**（比如部分地区的中国移动网络虽然解析路线是香港，但是无法连通）

Vercel国内连通性较好，所以还是会继续使用Vercel来托管的

## 测试截图
![Cloudflare](https://cdn.jsdelivr.net/gh/WenqiOfficial/wenqipic/img/cloudflare.png)
![Vercel](https://cdn.jsdelivr.net/gh/WenqiOfficial/wenqipic/img/vercel.png)
