### ISSUE TITLE
[Bug] 背景视频无法正常播放

### ISSUE THREAD

**Issue by 011231** [WenqiOfficial/StudyWithMiku#62]
### Bug简述

会反复的绿屏

### Bug复现

我在打开使用网站的时候就遇到了这个问题

### 预期行为

正常的话背景视频因该是不间断的播放

### 截图

![屏幕截图 2024-05-22 225401](https://github.com/WenqiOfficial/StudyWithMiku/assets/170545062/92074650-9e41-49ea-9e94-2b83fce522c7)

### 设备与系统环境

联想Y9000X IAH7

### 使用的浏览器

edge 123.0.2420.65

### 系统环境

window 11 64bit 23H2

**Comment by WenqiOfficial** [comment]
是关于背景不断闪回绿色画面吗

关于这个CDN的问题将会于今天晚上修复的( •̀ ω •́ )

**Comment by WenqiOfficial** [comment]
已修复( •̀ ω •́ )

**Comment by 011231** [comment]
辛苦了！


WenqiOfficial ***@***.***> 于2024年6月1日周六 17:25写道：
