### ISSUE TITLE
[Bug] 休息后切换按钮异常

### ISSUE THREAD

**Issue by gkgkhssy** [WenqiOfficial/StudyWithMiku#71]
### Bug简述

休息后切换播放按钮功能异常，无法正常切换播放暂停

### Bug复现

开始学习后，点击休息，此时切换按钮正常。回到学习后再次休息，切换按钮失效。
以上操作再次循环可稳定复现。

### 设备与系统环境

笔记本

### 使用的浏览器

Microsoft Edge 版本 119.0.2109.1 (正式版本) dev (64 位)

### 系统环境

Windows 11 专业版

**Comment by WenqiOfficial** [comment]
感谢小伙伴的反馈！(｀・ω・´)

是一个好久都没发现的逻辑BUG...（捂脸）

已经完成修复，试一试吧！(｀・ω・´)
