### ISSUE TITLE
Miku发呆

### ISSUE THREAD

**Issue by MHYCWasTaken** [WenqiOfficial/StudyWithMiku#9]
b站评论区好像也有类似的情况，那位是手机端切出去后再回来miku发呆  
我这电脑端息屏了一段时间回来miku也发呆，但是计时器计的时是没错的  
也许加一个刷新player的按钮（

**Comment by WenqiOfficial** [comment]
感谢反馈！

今天上午更新的版本中已经加入了定时刷新播放器了，如果卡住的话应该是视频加载问题了

这边也会尝试复现问题的( •̀ ω •́ )✧

**Comment by MHYCWasTaken** [comment]
~~那就没事了，我从上午开始就没刷新过~~

**Comment by WenqiOfficial** [comment]
www

如果Miku发呆还有他因的话就不好说了

刷新后试试看吧

如果还出现问题了也记得反馈噢( •̀ ω •́ )✧
